const gains = [
  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-17",
  },
  {
    description: "Conta de Luz",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Gasolina",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Cinema",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Conta de Luz",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Shopping",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Roupas",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Viagens",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Food",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Praias",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Conta de água",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Eventos",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Eletrônicos",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Compras do mês",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Internet",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Dentista",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },

  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-17",
  },
  {
    description: "Conta de Luz",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-19",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Gasolina",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Cinema",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Conta de Luz",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Shopping",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Roupas",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Viagens",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-07-19",
  },
  {
    description: "Food",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Praias",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Conta de água",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Eventos",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Eletrônicos",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-19",
  },
  {
    description: "Compras do mês",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-07-19",
  },
  {
    description: "Internet",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Dentista",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
  {
    description: "Passagem de onibûs",
    amount: "60.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-19",
  },
];

export default gains
